<?php

namespace Pi\FrontBundle\Repository;

/**
 * commentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findcomm($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select c from PiFrontBundle:comment c
    WHERE c.article_id=$id
      ");
        return $query->getResult();

    }

    public function UpdateEtat($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select COUNT (s) AS nb from PiFrontBundle:comment s
    WHERE s.article_id=$id 
      ");
        return $query->getResult();

    }

}
