<?php

namespace Pi\FrontBundle\Repository;

/**
 * PetsitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetsitterRepository extends \Doctrine\ORM\EntityRepository
{
}
