<?php

namespace Pi\adminBundle\Repository;

/**
 * AccessoiresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessoiresRepository extends \Doctrine\ORM\EntityRepository
{
    function findacc($no,$pr)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select a from PiAdminBundle:Accessoires a 
    WHERE a.nom LIKE :no AND a.prix LIKE :pr
      ")
            ->setParameter('no', '%' . $no . '%')->setParameter('pr', '%' . $pr . '%');
        return $query->getResult();
    }

    function findaccesp($cat)
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select a from PiAdminBundle:Accessoires a
     
     WHERE a.espece LIKE :cat 
     ")
            ->setParameter('cat', '%' . $cat . '%');

        return $query->getResult();

    }

}
