<?php

namespace Pi\adminBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function UpdateArticle()
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select COUNT (s) AS nb from PiAdminBundle:Article s
      ");
        return $query->getResult();

    }
}
