<?php

namespace Pi\adminBundle\Repository;

/**
 * assuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class assuranceRepository extends \Doctrine\ORM\EntityRepository
{

    public function UpdateAssur()
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select COUNT (s) AS nb from PiAdminBundle:assurance s
      ");
        return $query->getResult();

    }


}
