<?php

namespace Pi\adminBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function anciensEvenements()
    {
        $p=$this->getEntityManager()->createQuery('SELECT e FROM PiAdminBundle:Event e WHERE e.dateFin< CURRENT_DATE ()');
        return $p->getResult();
    }
}
