<?php

namespace Pi\adminBundle\Repository;

/**
 * VeterinairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeterinairesRepository extends \Doctrine\ORM\EntityRepository
{
  public function UpdateEtat()
    {
        $query = $this->getEntityManager()
            ->createQuery(" 
    select COUNT (s) AS nb from PiAdminBundle:Veterinaires s
      ");
        return $query->getResult();

    }



}
